pipeline:
  build:
    image: alpine:latest
    commands:
      - apk add --no-cache bash zip
      - VERSION=${CI_COMMIT_TAG#v}
      - mkdir -p build/plugin-reference-cleaner
      - cp plugin-reference-cleaner.php build/plugin-reference-cleaner/
      - cp readme.txt build/plugin-reference-cleaner/
      - cp LICENSE build/plugin-reference-cleaner/
      - cp README.md build/plugin-reference-cleaner/
      - cp CHANGELOG.md build/plugin-reference-cleaner/
      - cd build
      - zip -r ../plugin-reference-cleaner-$VERSION.zip plugin-reference-cleaner
      - cd ..
      
  release:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: gitea_token
      base_url: https://gitea.wpallstars.com
      files:
        - plugin-reference-cleaner-*.zip
      title: Release ${CI_COMMIT_TAG}
      note: |
        Plugin Reference Cleaner ${CI_COMMIT_TAG}
        
        See [CHANGELOG.md](https://gitea.wpallstars.com/wpallstars/plugin-reference-cleaner/src/branch/main/CHANGELOG.md) for details.

when:
  event: tag
  tag: v* 